= Vert.x Gradle Starter

This project is a example Vert.x project using Gradle.

== Prerequisites

* JDK 11+
* rxjava 2
* vertx
* docker
* Kafka
* Postgres
* Postman
* pgadmin

== Getting started

To build the project and generate jar
----
gradle build
----

Once you have retrieved the project, you can check that everything works with:
----
gradle test
----
or
----
./gradlew test run
----

The command compiles the project and runs the tests, then  it launches the application, so you can check by yourself. Open your browser to http://localhost:3001. You should see a _Hello World_ message.

== Before run the project

In (`docker`) folder you can find:

* Kafka
----
cd docker/kafka
docker-compose up -d
----

* postgres
----
docker pull postgres
docker run -d --name postgres -e POSTGRES_PASSWORD=password -p 5432:5432
----
With a sql client(For example: https://www.pgadmin.org/download/)
Create the table "testuser" with the columns

* id -> DataType: text Not NULL: true Primary Key: true
* name -> DataType: text Not NULL: false Primary Key: false

== After run the project

You can test the api with the postman collection(`postman/postman_collection.json`).
The collection is in the postman folder, it contains example requests to:

* Create user
* Update user
* Get user by id
* Get all users
* Delete user by id


== Anatomy of the project

The project use two verticles:

* *ApiVerticle* to receive rest requests and operates with
database[postgres] directly in query operations _(GET)_ and send events(_via kafka_) to command operations _(POST, PUT, DELETE)_.

* *EventsVerticle* receive the events and performs the operations on the database.

[ditaa]
----
                   +-------------------------+
                   |      Api Verticle       |
                   |                         |
                   +-------------------------+
                   |[GET] /users             |
    rest   -->     |[POST] /users            |<-----+
                   |[GET] /users/{userId}    |      |
                   |[UPDATE] /users/{userId} |      |
                   |[DELETE] /users/{userId} |      |
                   +-------------------------+      |
                        |                           |
                        | kafka                     |
                        |                           |
                        v                           |
                 /---------------\            +-----------+
   kafka topic   |incoming.users |            |           |
                 \---------------/            |  Postgres |
                        |                     |        {s}|
                        |                     +---+-------+
                        v                          ^
                   +--------+                      |
                   |        |                      |
                   | Events |                      |
                   |Verticle|----------------------+
                   |        |
                   +---+----+
----


== Building the project

To build the project, just use:

----
./gradlew build
----

It generates a _fat-jar_ in the `build/libs` directory.
